import uuid
from enum import Enum

from pydantic.fields import Field
from pydantic.main import BaseModel


class Item(BaseModel):
    """A model representing a supermarket product."""

    supermarket: str = Field(..., description="The name of the supermarket.")
    name: str = Field(..., description="The name of the product.")
    id: str = Field(default_factory=uuid.uuid4, description="The id of the product in the supermarket.")
    price: float = Field(..., description="The price of the product in the supermarket.")
    brand: str = Field(..., deøscription="The price of the product in the supermarket.")
    product: str = Field(..., description="The category of the product in the supermarket.")
    quantity: float = Field(..., description="The dimension in grams/l of the product in the supermarket.")
    link: str = Field(..., description="The link to the product.")
    rank: int = Field(..., description="The rank of the product.")
    offer: str | None = Field(..., description="The offer on the product.")
    description: str | None = Field(..., description="The description on the product.")


class Product:
    """All product buckets."""

    values = [
        "agrumi",
        "frutta sciroppata",
        "frutta secca",
        "noci",
        "mandorle",
        "mele",
        "pere",
        "banane",
        "insalate verdi",
        "legumi",
        "olive",
        "verdura fresca",
        "ortaggi",
        "formaggi a pasta filata",
        "formaggi a pasta molle",
        "formaggi muffettati",
        "grana",
        "parmigiano",
        "pecorino",
        "formaggi spalmabili",
        "burro",
        "latte",
        "panna",
        "uova",
        "budini",
        "dessert",
        "yogurt",
        "probiotici",
        "carne",
        "bovino",
        "vitello",
        "pollo",
        "tacchino",
        "suino",
        "pesce",
        "banco freschi",
        "gastronomia",
        "affettati",
        "prosciutto",
        "prosciutto cotto",
        "prosciutto crudo",
        "bresaola",
        "philadelphia",
        "salumi",
        "wurstel",
        "crackers",
        "farina",
        "fette biscottate",
        "grissini",
        "pane",
        "pasta di semola",
        "pasta fresca",
        "polenta",
        "purè",
        "riso",
        "risotti in busta",
        "pane",
        "caffe",
        "orzo solubili",
        "caffe in cialde",
        "caffe in capsule",
        "caffe in grani",
        "caffe tostato",
        "te",
        "infusi",
        "tisane",
        "camomilla",
        "aceto",
        "dadi",
        "ketchup",
        "maionese",
        "sale",
        "salse",
        "spezie e aromi",
        "piatti pronti",
        "sottolio e sottaceti",
        "tonno",
        "pesce in scatola",
        "verdure in scatola",
        "olio di oliva extra vergine",
        "olio di semi",
        "pelati",
        "passate",
        "sughi in barattolo",
        "sugo di pomodoro",
        "pesto genovese",
        "biscotti",
        "caramelle",
        "chewingum",
        "cereali e muesli",
        "cioccolato e spalmabili",
        "confetture",
        "miele",
        "pasticceria secca",
        "preparati per dolci",
        "zucchero",
        "dolcificanti",
        "merendine",
        "snack dolci",
        "patatine",
        "snack salati",
        "acqua minerale",
        "acqua naturale",
        "aperitivi alcolici",
        "aperitivi analcolici",
        "birre",
        "bevande",
        "bibite gassate",
        "energy drink",
        "integratori salini",
        "succhi di frutta",
        "liquori",
        "superalcolici",
        "amari e chine",
        "distillati",
        "prosecco",
        "spumanti",
        "champagne",
        "vini bianchi",
        "vini da tavola",
        "vini rossi",
        "surgelati",
        "gelati",
        "patate surgelate",
        "pesce surgelato",
        "piatti pronti",
        "pizze",
        "torte salate",
        "verdura surgelata",
        "pannolini",
        "salviettine",
        "alimenti per cani",
        "alimenti per gatti",
        "animali",
        "balsami",
        "gel",
        "lacca e schiume",
        "shampoo",
        "cura del corpo",
        "assorbenti",
        "bagnoschiuma",
        "cotone",
        "creme per il corpo",
        "cura mani e piedi",
        "deodoranti persona",
        "igiene intima",
        "integratori",
        "lamette e rasoi",
        "medicazione",
        "prodotti viso",
        "profumi",
        "saponette",
        "saponi liquidi",
        "schiume da barba",
        "spugne e pettini",
        "collutori",
        "dentifrici",
        "prodotti per dentiere",
        "spazzolini",
        "alluminio",
        "pellicola",
        "carta igienica",
        "fazzoletti di carta",
        "rotoli",
        "asciugatutto",
        "tovaglioli di carta",
        "ammorbidenti",
        "candeggina",
        "ammoniaca",
        "detergenti bagno",
        "detersivi casa",
        "detersivi per lavastoviglie",
        "detersivi per lavatrice",
        "detersivi piatti",
        "liquidi per pavimenti",
        "panni e spugne",
        "sacchi e guanti",
        "smacchiatori",
        "sbiancanti",
        "piccoli elettrodomestici",
    ]


class Supermarket(str, Enum):
    """Supported supermarkets."""

    COOP = "Coop"
    LIDL = "Lidl"
    MIGROS = "Migros"

    # ...
    # TODO: complete the other supermarkets
